name: pipecat_test

services:
  voxkit:
    build:
      context: .
      dockerfile: Dockerfile
    image: zeeshanahmed2798/voxkit-pipecat:latest
    container_name: voxkit-pipecat
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DAILY_API_KEY: ${DAILY_API_KEY}
      DAILY_API_URL: ${DAILY_API_URL}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      SONIOX_API_KEY: ${SONIOX_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: ${PORT}



